name: build

on:
  push:
    branches:
      - main

jobs:
  BuildRelease:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    name: Checkout Code
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
      - name: Build and Release
        uses: jupiterone/action-node-build-release@init-testing
        with:
          npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}
          gh_token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}