openapi: 3.0.1
info:
  title: action-npm-build-release
  description: ''
  x-cortex-git:
    github:
      repository: JupiterOne/action-npm-build-release
  x-cortex-owners:
    - type: group
      name: JupiterOne/security
  x-cortex-service-groups: tier-4
  x-cortex-tag: action-npm-build-release
